name: Grow
on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - main
    paths:
      - 'config/x86_64.config'
  schedule:
    - cron: 0 4 * * 5
  watch:
    types: started
jobs:
  downloading:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare your file
      run: |
        mkdir download
        git clone "https://github.com/terrydash/Grow.wiki.git"
        wiki=`echo $echo $GITHUB_REPOSITORY | cut -d "/" -f 2`.wiki
        cd "$wiki"
        drive=`git log --pretty=format: -1 --name-only *.md`
        export drive
        cd ..
        wget -q `cat $wiki/$drive | xargs` --directory-prefix=download
    - name: Upload your file
      run: |
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet ./download/

