name: Grow
on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - main
    paths:
      - 'config/x86_64.config'
  schedule:
    - cron: 0 4 * * 5
  watch:
    types: started
jobs:
  downloading:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare your file
      run: |
        mkdir download
        wget -q https://github.com/terrydash/Openwrt-Diy/suites/1283030790/artifacts/19935137 --directory-prefix=download
    - name: Upload your file
      run: |
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet ./download/

